create database zepto;
use zepto;
show tables;
select * from zepto;

-- =========================================================
-- ZEPTO INVENTORY ANALYSIS USING MYSQL
-- =========================================================
-- Project Objective:
-- Analyze Zepto inventory data to generate business insights
-- related to pricing, discounts, inventory management,
-- product availability, and estimated revenue.
-- =========================================================



-- =========================================================
-- DATA EXPLORATION
-- =========================================================

-- Q1. View the complete dataset.
SELECT * 
FROM zepto;


-- Q2. Find the total number of records available in the dataset.
SELECT COUNT(*) AS total_records
FROM zepto;


-- Q3. Preview the first 10 rows of the dataset.
SELECT *
FROM zepto
LIMIT 10;


-- =========================================================
-- DATA QUALITY CHECKS
-- =========================================================

-- Q4. Identify records containing NULL values.
SELECT *
FROM zepto
WHERE category IS NULL
   OR name IS NULL
   OR mrp IS NULL
   OR discountPercent IS NULL
   OR availableQuantity IS NULL
   OR discountedSellingPrice IS NULL
   OR weightInGms IS NULL
   OR outOfStock IS NULL
   OR quantity IS NULL;


-- Q5. Find all unique product categories available in the dataset.
SELECT DISTINCT category
FROM zepto
ORDER BY category;


-- Q6. Analyze product availability status (In Stock vs Out of Stock).
SELECT 
    outOfStock,
    COUNT(*) AS total_products
FROM zepto
GROUP BY outOfStock;


-- Q7. Identify products that appear multiple times in the dataset.
SELECT 
    name,
    COUNT(*) AS total_count
FROM zepto
GROUP BY name
HAVING total_count > 1
ORDER BY total_count DESC;



-- =========================================================
-- DATA CLEANING
-- =========================================================

-- Q8. Find products where MRP is equal to zero.
SELECT 
    name AS product_name
FROM zepto
WHERE mrp = 0;


-- Q9. Remove products with invalid MRP values.
DELETE FROM zepto
WHERE mrp = 0;


-- Q10. Convert MRP and discounted selling price from paise to rupees.

UPDATE zepto
SET 
    mrp = mrp / 100,
    discountedSellingPrice = discountedSellingPrice / 100;


-- Q11. Verify updated price columns after conversion.
SELECT 
    mrp,
    discountedSellingPrice
FROM zepto;



-- =========================================================
-- BUSINESS INSIGHTS ANALYSIS
-- =========================================================

-- Q12. Find the top 10 best-value products based on discount percentage.
SELECT 
    name,
    discountPercent
FROM zepto
ORDER BY discountPercent DESC
LIMIT 10;


-- Q13. Identify high-MRP products that are currently out of stock.
SELECT DISTINCT
    name,
    mrp
FROM zepto
WHERE outOfStock = 'TRUE'
ORDER BY mrp DESC;


-- Q14. Calculate the estimated revenue generated by each product category.
-- Formula Used:
-- Estimated Revenue = Discounted Selling Price × Available Quantity
SELECT 
    category,
    SUM(discountedSellingPrice * availableQuantity) AS estimated_revenue
FROM zepto
GROUP BY category
ORDER BY estimated_revenue DESC;


-- Q15. Find products where MRP is greater than ₹500 and discount percentage is less than 10%.
SELECT DISTINCT
    name
FROM zepto
WHERE mrp > 500
  AND discountPercent < 10;


-- Q16. Identify the top 5 categories offering the highest average discount percentage.
SELECT 
    category,
    AVG(discountPercent) AS average_discount_percentage
FROM zepto
GROUP BY category
ORDER BY average_discount_percentage DESC
LIMIT 5;


-- Q17. Calculate price per gram for products above 100g and identify the best-value products.
SELECT DISTINCT
    name,
    weightInGms,
    discountedSellingPrice,
    ROUND(discountedSellingPrice / weightInGms, 2) AS price_per_gram
FROM zepto
WHERE weightInGms >= 100
ORDER BY price_per_gram;


-- Q18. Categorize products based on weight into Low, Medium, and Bulk categories.
SELECT DISTINCT
    name,
    CASE
        WHEN weightInGms < 1000 THEN 'Low'
        WHEN weightInGms < 5000 THEN 'Medium'
        ELSE 'Bulk'
    END AS weight_category
FROM zepto;


-- Q19. Calculate the total inventory weight available in each category.
SELECT 
    category,
    SUM(weightInGms * availableQuantity) AS total_inventory_weight
FROM zepto
GROUP BY category
ORDER BY total_inventory_weight DESC;

-- Q20. Rank products based on highest discount percentage.
SELECT
    name,
    category,
    discountPercent,
    Dense_RANK() OVER (ORDER BY discountPercent DESC) AS discount_rank
FROM zepto;


-- Q21. Find the top 3 most expensive products in each category.
SELECT *
FROM (
    SELECT
        name,category,mrp,
        RANK() OVER (
            PARTITION BY category
            ORDER BY mrp DESC
        ) AS product_rank
    FROM zepto
) ranked_products
WHERE product_rank <= 3;


-- Q22. Calculate running total of estimated revenue across products.
SELECT
    name,
    category,
    discountedSellingPrice,
    availableQuantity,
    (discountedSellingPrice * availableQuantity) AS estimated_revenue,
    SUM(discountedSellingPrice * availableQuantity)
    OVER (ORDER BY discountedSellingPrice * availableQuantity DESC)
    AS running_total_revenue
FROM zepto;






-- =========================================================
-- END OF PROJECT
-- =========================================================

